replicas: 2

image:
  pullPolicy: Always
  tag: ubuntu-16.04
  repository: toilregistry.azurecr.io/azpagent
  imagePullSecret: test22

podName: azp-agent

resources:
  disk: "10Gi"

volumeMounts: |
  - name: dockersock
    mountPath: "/var/run/docker.sock"

volumes: |
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock

cleanRun: false

extraEnv: {}
